[package]
name = "mysql-rent"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.6"
wait = { git = "https://github.com/ufoscout/docker-compose-wait" }
mysql_async = "0.28.0"
chrono = "0.4.19"
tokio = { version = "1.9.0", features = [ "full" ] } 
